import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

/**
 * ESLint 9 flat config.
 *
 * `eslint-config-next` is still published as an eslintrc-style config, so it is
 * bridged through FlatCompat rather than imported directly.
 */
const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      '.next/**',
      // The production build's distDir (next.config.ts reads NEXT_DIST_DIR so
      // that `next build` never overwrites the `.next` a dev server is using).
      // Without this entry eslint walks the emitted bundles.
      '.next-prod/**',
      'node_modules/**',
      '.data/**',
      // Playwright/Next audit builds are intentionally kept under tmp/ for
      // local investigation. They are emitted code, never source files.
      'tmp/**',
      'test-results/**',
      'playwright-report/**',
      // Regenerated by Next on every build.
      'next-env.d.ts',
    ],
  },
  {
    rules: {
      // The generated-media surfaces render runtime URLs from the artifact
      // store, which next/image cannot optimise; those sites opt out inline.
      '@next/next/no-img-element': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
]

export default config
