import { expect, test } from '@playwright/test'

test.describe('Skill authoring lifecycle', () => {
  test.beforeEach(async ({ request }) => { await request.post('/api/dev/reset') })

  test('aligns 我的 entry copy and publishes a reviewed local Skill into 我的 before unpublishing it', async ({ page }) => {
    await page.goto('/skills')
    await expect(page.getByRole('heading', { name: '新的一天，新的 Skill' })).toBeVisible()
    await page.getByTestId('skill-collection-我的').click()
    await expect(page.getByTestId('skill-author-entry')).toContainText('我的 Skill')
    await expect(page.getByTestId('skill-author-open')).toHaveText('创建Skill')
    await page.getByTestId('skill-author-open').click()
    const studio = page.getByTestId('skill-author-studio')
    await expect(studio).toContainText('还没有自建 Skill')
    await studio.getByTestId('skill-author-create').click()
    await studio.getByTestId('skill-author-name').fill('镜头节奏助手')
    await studio.getByTestId('skill-author-summary').fill('将镜头表整理为节奏明确、可执行的短片创作任务。')
    await studio.getByTestId('skill-author-usage-scenarios').fill('适用于脚本定稿后需要明确镜头节奏的短片创作。')
    await studio.getByTestId('skill-author-how-to-use').fill('输入镜头表与目标时长，调用后确认镜头节奏。')
    await studio.getByTestId('skill-author-output-content').fill('返回镜头节奏表、转场建议与可执行镜头清单。')
    await studio.getByTestId('skill-author-output-type-image').check()
    await studio.getByTestId('skill-author-output-type-video').check()
    await studio.getByTestId('skill-author-cover').fill('/fixtures/libtv/skills/example-01.svg')
    await studio.getByTestId('skill-author-version').fill('1.2.0')
    await studio.getByTestId('skill-author-save').click()
    await studio.getByTestId('skill-author-submit-review').click()
    await expect(studio.getByTestId('skill-author-status')).toContainText('审核通过，待发布')
    await studio.getByTestId('skill-author-publish').click()
    await expect(studio.getByTestId('skill-author-status')).toContainText('已发布')
    // Dialog has both a backdrop and titlebar close affordance. Escape matches
    // the documented product shortcut and avoids coupling this journey to their
    // DOM order.
    await page.keyboard.press('Escape')
    await expect(studio).toBeHidden()
    await expect(page.getByTestId('skill-card-skill-local-001')).toContainText('镜头节奏助手')

    await page.getByTestId('skill-author-open').click()
    await studio.getByTestId('skill-author-unpublish').click()
    await expect(studio.getByTestId('skill-author-status')).toContainText('已下架')
  })
})

test.describe('Skill authoring direct routes', () => {
  test.beforeEach(async ({ request }) => { await request.post('/api/dev/reset') })

  test('authors, versions, reviews and publishes a local Skill from the observed singular create route', async ({ page }) => {
    await page.goto('/skill/create')
    await expect(page).toHaveURL(/\/skill\/create$/)
    await expect(page.getByTestId('skill-author-page')).toBeVisible()
    const studio = page.getByTestId('skill-author-studio')
    const workbench = studio.locator('[aria-busy]')
    await expect(studio).toContainText('还没有自建 Skill')

    await studio.getByTestId('skill-author-create').click()
    await studio.getByTestId('skill-author-name').fill('视频镜头连续性助手')
    await studio.getByTestId('skill-author-summary').fill('把分镜和角色参考整理成可连续执行的视频镜头任务。')
    await studio.getByTestId('skill-author-usage-scenarios').fill('适用于短片分镜已经确认、准备衔接连续视频镜头的阶段。')
    await studio.getByTestId('skill-author-how-to-use').fill('输入分镜、角色资产和目标时长，再确认转场与镜头顺序。')
    await studio.getByTestId('skill-author-output-content').fill('返回连续镜头表、角色锚点和可直接生成的视频提示词。')
    await studio.getByTestId('skill-author-output-type-video').check()
    await studio.getByTestId('skill-author-version').fill('1.4.0')
    await studio.getByTestId('skill-author-save').click()
    await expect(workbench).toHaveAttribute('aria-busy', 'false')
    await studio.getByTestId('skill-author-submit-review').click()
    await expect(studio.getByTestId('skill-author-status')).toContainText('审核通过，待发布')
    await expect(workbench).toHaveAttribute('aria-busy', 'false')
    await studio.getByTestId('skill-author-publish').click()
    await expect(studio.getByTestId('skill-author-status')).toContainText('已发布')
    await expect(workbench).toHaveAttribute('aria-busy', 'false')

    await studio.getByTestId('skill-author-unpublish').click()
    await expect(studio.getByTestId('skill-author-status')).toContainText('已下架')
    await expect(workbench).toHaveAttribute('aria-busy', 'false')
    await studio.getByTestId('skill-author-version').fill('1.5.0')
    await studio.getByTestId('skill-author-save').click()
    await expect(studio.getByTestId('skill-author-status')).toContainText('已下架')
    await expect(workbench).toHaveAttribute('aria-busy', 'false')
    await studio.getByTestId('skill-author-submit-review').click()
    await expect(workbench).toHaveAttribute('aria-busy', 'false')
    await studio.getByTestId('skill-author-publish').click()
    await expect(studio.getByTestId('skill-author-status')).toContainText('已发布')

    await page.goto('/skills/create')
    await expect(page).toHaveURL(/\/skills\/create$/)
    await expect(page.getByTestId('skill-author-page')).toBeVisible()
    await expect(page.getByTestId('skill-author-status')).toContainText('已发布')
  })
})
